// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info is the validated, UI-facing licence state.
 */
export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("hasLicence" in $$source)) {
            /**
             * a licence string is installed (valid or not)
             * @member
             * @type {boolean}
             */
            this["hasLicence"] = false;
        }
        if (!("licensed" in $$source)) {
            /**
             * installed, signature-valid AND not expired
             * @member
             * @type {boolean}
             */
            this["licensed"] = false;
        }
        if (!("customer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["customer"] = "";
        }
        if (!("tier" in $$source)) {
            /**
             * @member
             * @type {Tier}
             */
            this["tier"] = Tier.$zero;
        }
        if (!("seats" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seats"] = 0;
        }
        if (!("expires" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expires"] = "";
        }
        if (!("expired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["expired"] = false;
        }
        if (!("err" in $$source)) {
            /**
             * why an installed licence isn't valid
             * @member
             * @type {string}
             */
            this["err"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}

/**
 * Tier is the licence level. Personal is the implicit free default (no licence).
 * @readonly
 * @enum {string}
 */
export const Tier = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TierPersonal: "personal",
    TierBusiness: "business",
};
