// Package license verifies Nimbo business licences. A licence is a signed,
// offline-verifiable token: base64url(claims-json) "." base64url(ed25519-sig),
// prefixed "NIMBO-LIC-1.". The signing public key is embedded below; the
// matching private key is held only by Otherworld Dev Ltd and never ships, so
// a valid licence can only be issued by us — no server check, no phone-home.
//
// Licensing gates only BUSINESS-tier capabilities (central policy, white-label,
// …). Every feature that is free today stays free without any licence.
package license

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"errors"
	"os"
	"strings"
	"time"
)

// SigningPublicKey is Nimbo's licence-signing public key (Ed25519, 32 bytes).
// Generated by tools/licensegen; the private half lives only off-repo.
var SigningPublicKey = ed25519.PublicKey{
	0xdc, 0xa1, 0x28, 0xb5, 0x9d, 0x85, 0xf1, 0x37, 0xa3, 0xed, 0x4d, 0x51,
	0x1a, 0x0e, 0x8d, 0x02, 0xdb, 0x61, 0x83, 0x7f, 0x88, 0x58, 0xbf, 0x7e,
	0x56, 0x63, 0xe4, 0x77, 0x36, 0xcb, 0xd0, 0x47,
}

const tokenPrefix = "NIMBO-LIC-1."

// Tier is the licence level. Personal is the implicit free default (no licence).
type Tier string

const (
	TierPersonal Tier = "personal"
	TierBusiness Tier = "business"
)

// Claims is the signed payload of a licence.
type Claims struct {
	Customer string `json:"customer"`          // who it's issued to (shown in the UI)
	Tier     Tier   `json:"tier"`              // "business"
	Seats    int    `json:"seats"`             // licensed seat count (0 = unspecified)
	Issued   string `json:"issued"`            // YYYY-MM-DD
	Expires  string `json:"expires,omitempty"` // YYYY-MM-DD; empty = perpetual
	ID       string `json:"id"`                // unique licence id (for our records)
}

// Info is the validated, UI-facing licence state.
type Info struct {
	HasLicence bool   `json:"hasLicence"` // a licence string is installed (valid or not)
	Licensed   bool   `json:"licensed"`   // installed, signature-valid AND not expired
	Customer   string `json:"customer"`
	Tier       Tier   `json:"tier"`
	Seats      int    `json:"seats"`
	Expires    string `json:"expires"`
	Expired    bool   `json:"expired"`
	Err        string `json:"err"` // why an installed licence isn't valid
}

// Verify checks a licence token's signature against the embedded public key and
// returns its claims. Purely offline. It does NOT check expiry — see Evaluate.
func Verify(token string) (Claims, error) {
	token = strings.TrimSpace(token)
	token = strings.TrimPrefix(token, tokenPrefix)
	if len(SigningPublicKey) != ed25519.PublicKeySize {
		return Claims{}, errors.New("licence verification unavailable (no signing key)")
	}
	parts := strings.SplitN(token, ".", 2)
	if len(parts) != 2 {
		return Claims{}, errors.New("not a valid licence key (wrong format)")
	}
	payload, err := base64.RawURLEncoding.DecodeString(parts[0])
	if err != nil {
		return Claims{}, errors.New("not a valid licence key (bad payload)")
	}
	sig, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return Claims{}, errors.New("not a valid licence key (bad signature)")
	}
	if !ed25519.Verify(SigningPublicKey, payload, sig) {
		return Claims{}, errors.New("licence signature is invalid")
	}
	var c Claims
	if err := json.Unmarshal(payload, &c); err != nil {
		return Claims{}, errors.New("not a valid licence key (bad claims)")
	}
	return c, nil
}

// expired reports whether c has an expiry date in the past (a full day of grace
// past midnight of the expiry date).
func (c Claims) expired(now time.Time) bool {
	if c.Expires == "" {
		return false
	}
	t, err := time.Parse("2006-01-02", c.Expires)
	if err != nil {
		return false // unparseable expiry → treat as perpetual rather than locking out
	}
	return now.After(t.Add(24 * time.Hour))
}

// Evaluate validates a stored token into UI-facing Info as of now. An empty
// token yields the unlicensed (free personal) state with no error.
func Evaluate(token string, now time.Time) Info {
	if strings.TrimSpace(token) == "" {
		return Info{}
	}
	c, err := Verify(token)
	if err != nil {
		return Info{HasLicence: true, Err: err.Error()}
	}
	exp := c.expired(now)
	info := Info{
		HasLicence: true,
		Licensed:   !exp,
		Customer:   c.Customer,
		Tier:       c.Tier,
		Seats:      c.Seats,
		Expires:    c.Expires,
		Expired:    exp,
	}
	if exp {
		info.Err = "licence expired on " + c.Expires
	}
	return info
}

// Allows reports whether info grants at least tier t. Business is currently the
// only paid tier; personal needs no licence.
func (i Info) Allows(t Tier) bool {
	if t == TierPersonal {
		return true
	}
	return i.Licensed && i.Tier == TierBusiness
}

// Load reads a licence token from path ("" if the file is absent).
func Load(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}

// Save writes a licence token to path (0600 — it's a paid credential).
func Save(path, token string) error {
	return os.WriteFile(path, []byte(strings.TrimSpace(token)+"\n"), 0o600)
}

// Remove deletes the stored licence (no error if absent).
func Remove(path string) error {
	err := os.Remove(path)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}
