// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails-bound service: its exported methods are callable from the
 * frontend, and it forwards engine changes to the UI as events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as license$0 from "../../internal/license/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AccountInfo returns the current account, if signed in.
 * @returns {$CancellablePromise<$models.AccountDTO>}
 */
export function AccountInfo() {
    return $Call.ByID(611470312).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ActivateLicence validates a pasted licence token and, if valid, installs it.
 * Returns "" on success or a human-readable reason it was rejected.
 * @param {string} token
 * @returns {$CancellablePromise<string>}
 */
export function ActivateLicence(token) {
    return $Call.ByID(1918100155, token);
}

/**
 * AddAccount opens the sign-in window to connect another Nextcloud account.
 * The completed login becomes the active account (see account.Complete).
 * @returns {$CancellablePromise<void>}
 */
export function AddAccount() {
    return $Call.ByID(3517798243);
}

/**
 * AddExclude / RemoveExclude toggle selective-sync excludes within a pair.
 * @param {string} localDir
 * @param {string} rel
 * @returns {$CancellablePromise<void>}
 */
export function AddExclude(localDir, rel) {
    return $Call.ByID(2544922982, localDir, rel);
}

/**
 * AddSyncFolder / RemoveSyncFolder add or remove a synced folder.
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function AddSyncFolder(remotePath) {
    return $Call.ByID(2184709083, remotePath);
}

/**
 * AddSyncPair sets up a sync connection from a remote folder to an explicit
 * local directory. Returns "" on success or an error message for the UI.
 * @param {string} localDir
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function AddSyncPair(localDir, remotePath) {
    return $Call.ByID(3205509215, localDir, remotePath);
}

/**
 * AppDockSide reports which edge the app dock sits on: "right" (default),
 * "left", or "bottom".
 * @returns {$CancellablePromise<string>}
 */
export function AppDockSide() {
    return $Call.ByID(3763787832);
}

/**
 * ApplyUpdate installs the latest release and relaunches. Nimbo closes partway
 * through (the package can't update while running). Returns "" once the update
 * helper has started, or an error message.
 * 
 * It installs the release's own versioned .msix asset URL (from the GitHub API)
 * rather than going through the latest/download App Installer feed: both
 * GitHub's CDN alias and Windows' cached copy of the .appinstaller can lag a
 * release, making Add-AppxPackage conclude "already up to date" and "succeed"
 * without changing the installed version. A per-version asset URL can't be
 * stale.
 * @returns {$CancellablePromise<string>}
 */
export function ApplyUpdate() {
    return $Call.ByID(4175318290);
}

/**
 * Apps returns the account's Nextcloud apps, marking which are pinned.
 * @returns {$CancellablePromise<$models.AppInfo[]>}
 */
export function Apps() {
    return $Call.ByID(1122244149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Attention reports how many conflicts and can't-sync files are outstanding.
 * @returns {$CancellablePromise<$models.AttentionInfo>}
 */
export function Attention() {
    return $Call.ByID(3677252977).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function AutostartEnabled() {
    return $Call.ByID(3995382427);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function AutostartSupported() {
    return $Call.ByID(978223476);
}

/**
 * BeginLogin starts Login Flow v2: it opens the browser and polls in the
 * background, emitting "login:done" or "login:error". Returns the login URL (or
 * an "error: …" string if it couldn't start).
 * @param {string} server
 * @returns {$CancellablePromise<string>}
 */
export function BeginLogin(server) {
    return $Call.ByID(2848527667, server);
}

/**
 * BlacklistBlocked stops attempting to sync a blocked file.
 * @param {string} abs
 * @returns {$CancellablePromise<void>}
 */
export function BlacklistBlocked(abs) {
    return $Call.ByID(3503220548, abs);
}

/**
 * BlockedList returns files that can't sync.
 * @returns {$CancellablePromise<$models.BlockedItem[]>}
 */
export function BlockedList() {
    return $Call.ByID(1761038307).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Brand returns this build's brand identity for the UI.
 * @returns {$CancellablePromise<$models.BrandDTO>}
 */
export function Brand() {
    return $Call.ByID(2741044894).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * BrowseOffline lists the shown account's virtual-root folders at rel ("" =
 * root) with their pin state, for the available-offline panel. Only folders
 * that already exist locally as placeholders appear (the tree populates as
 * it's browsed).
 * @param {string} rel
 * @returns {$CancellablePromise<$models.OfflineEntry[]>}
 */
export function BrowseOffline(rel) {
    return $Call.ByID(1230839982, rel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * BrowseRemote lists a remote directory (one level), excluding the dir itself.
 * @param {string} path
 * @returns {$CancellablePromise<$models.BrowseEntry[]>}
 */
export function BrowseRemote(path) {
    return $Call.ByID(2062198093, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * CanApplyUpdate reports whether Nimbo can update itself in place (a packaged
 * install on Windows). The frontend offers "Update now" only when true; loose
 * dev builds fall back to opening the release page.
 * @returns {$CancellablePromise<boolean>}
 */
export function CanApplyUpdate() {
    return $Call.ByID(1518664850);
}

/**
 * CheckForUpdate queries the GitHub releases for a newer build.
 * @returns {$CancellablePromise<$models.UpdateDTO>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2347956003).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ClearStatusMessage clears the custom status message.
 * @returns {$CancellablePromise<void>}
 */
export function ClearStatusMessage() {
    return $Call.ByID(3810724371);
}

/**
 * CloseLogin closes the sign-in window.
 * @returns {$CancellablePromise<void>}
 */
export function CloseLogin() {
    return $Call.ByID(3367834488);
}

/**
 * CompleteSetup applies the chosen initial-sync option for the whole account
 * into localDir, then finishes onboarding. mode is one of:
 * 
 * 	"everything" — classic two-way sync of the entire account
 * 	"choose"     — set the base dir only; the caller opens Sync settings to pick
 * 	"ondemand"   — virtual files (Cloud Files placeholders, download on open)
 * 
 * Returns "" on success or an error message for the UI.
 * @param {string} localDir
 * @param {string} mode
 * @returns {$CancellablePromise<string>}
 */
export function CompleteSetup(localDir, mode) {
    return $Call.ByID(507086583, localDir, mode);
}

/**
 * ConflictPreview returns a short text sample of each side of a pending conflict.
 * Binary files report a note instead of garbled text; the remote stream is closed
 * after the sample, so large files aren't fully downloaded just to preview them.
 * @param {string} localDir
 * @param {string} path
 * @returns {$CancellablePromise<$models.ConflictPreview>}
 */
export function ConflictPreview(localDir, path) {
    return $Call.ByID(478830689, localDir, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * Conflicts returns the pending conflicts, each enriched with per-side metadata.
 * @returns {$CancellablePromise<$models.ConflictItem[]>}
 */
export function Conflicts() {
    return $Call.ByID(3997271276).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * CopyToClipboard copies text (e.g. a share link) to the system clipboard.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function CopyToClipboard(text) {
    return $Call.ByID(1438304177, text);
}

/**
 * CreatePublicLink creates a public-link share on the target path. password and
 * expiration ("YYYY-MM-DD") are optional. Returns "" on success or an error.
 * @param {string} password
 * @param {string} expiration
 * @param {boolean} allowEdit
 * @returns {$CancellablePromise<string>}
 */
export function CreatePublicLink(password, expiration, allowEdit) {
    return $Call.ByID(3638868848, password, expiration, allowEdit);
}

/**
 * CreateUserShare shares the target path with another user. Returns "" on success.
 * @param {string} user
 * @param {boolean} allowEdit
 * @returns {$CancellablePromise<string>}
 */
export function CreateUserShare(user, allowEdit) {
    return $Call.ByID(2850199977, user, allowEdit);
}

/**
 * DeleteAllBlocked deletes every blocked file from disk; returns the count removed.
 * @returns {$CancellablePromise<number>}
 */
export function DeleteAllBlocked() {
    return $Call.ByID(178473519);
}

/**
 * DeleteBlocked deletes a blocked file from disk (it can't sync because of its name).
 * @param {string} abs
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBlocked(abs) {
    return $Call.ByID(2504910566, abs);
}

/**
 * DeleteShare removes a share by ID. Returns "" on success.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function DeleteShare(id) {
    return $Call.ByID(3403951449, id);
}

/**
 * DeleteTrash permanently deletes a trashed item by href. Returns "" on success.
 * @param {string} href
 * @returns {$CancellablePromise<string>}
 */
export function DeleteTrash(href) {
    return $Call.ByID(4036360776, href);
}

/**
 * DeselectFolder stops syncing rel within the pair at localDir. The server copy is
 * always kept; deleteLocal also removes the downloaded local copy to free space.
 * Returns "" on success or an error string.
 * @param {string} localDir
 * @param {string} rel
 * @param {boolean} deleteLocal
 * @returns {$CancellablePromise<string>}
 */
export function DeselectFolder(localDir, rel, deleteLocal) {
    return $Call.ByID(1961239194, localDir, rel, deleteLocal);
}

/**
 * Diagnostics returns Nimbo's current health (no network calls) for the UI.
 * @returns {$CancellablePromise<$models.DiagnosticsDTO>}
 */
export function Diagnostics() {
    return $Call.ByID(4058123183).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * DismissAllNotifications clears every notification for the active account.
 * @returns {$CancellablePromise<void>}
 */
export function DismissAllNotifications() {
    return $Call.ByID(1277895762);
}

/**
 * DismissNotification removes a notification by ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DismissNotification(id) {
    return $Call.ByID(201519076, id);
}

/**
 * DoNotificationAction runs a notification's action by label.
 * @param {number} id
 * @param {string} label
 * @returns {$CancellablePromise<void>}
 */
export function DoNotificationAction(id, label) {
    return $Call.ByID(3836520033, id, label);
}

/**
 * EnterSetup resizes the sign-in window to fit the configuration screen.
 * @returns {$CancellablePromise<void>}
 */
export function EnterSetup() {
    return $Call.ByID(1556398822);
}

/**
 * FlyoutAppearance returns the current flyout appearance, with defaults filled in.
 * @returns {$CancellablePromise<$models.FlyoutAppearanceDTO>}
 */
export function FlyoutAppearance() {
    return $Call.ByID(1978346652).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * Folders returns the quick-open folders for the flyout: live sync pairs plus
 * any on-demand (virtual files) mounts.
 * @returns {$CancellablePromise<$models.FolderInfo[]>}
 */
export function Folders() {
    return $Call.ByID(727328098).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * FreeSpace reports the free bytes on the volume holding dir (for live updates
 * as the user picks a different folder).
 * @param {string} dir
 * @returns {$CancellablePromise<number>}
 */
export function FreeSpace(dir) {
    return $Call.ByID(163121935, dir);
}

/**
 * GetAllowedFilenames returns the filenames the user permits even when normally
 * blocked (the builtin web-config block — .htaccess/.htpasswd/.user.ini — or the
 * server's forbidden list).
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAllowedFilenames() {
    return $Call.ByID(1844951149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetBaseDir / SetBaseDir manage the local root for newly-synced folders.
 * @returns {$CancellablePromise<string>}
 */
export function GetBaseDir() {
    return $Call.ByID(1204833849);
}

/**
 * GetConflictPolicy returns the saved default conflict policy.
 * @returns {$CancellablePromise<string>}
 */
export function GetConflictPolicy() {
    return $Call.ByID(2413247111);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetIgnore() {
    return $Call.ByID(1021506421).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetIgnorePatterns returns the global ignore patterns (one glob per entry) that
 * exclude matching paths from every sync pair, on top of Nimbo's built-in
 * defaults (node_modules, .git, OS/editor cruft, …).
 * @returns {$CancellablePromise<string[]>}
 */
export function GetIgnorePatterns() {
    return $Call.ByID(4086853534).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.LimitsDTO>}
 */
export function GetLimits() {
    return $Call.ByID(3287149099).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetPairs returns configured sync pairs.
 * @returns {$CancellablePromise<$models.PairDTO[]>}
 */
export function GetPairs() {
    return $Call.ByID(1028120708).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetPauseSchedule returns the saved quiet-hours window.
 * @returns {$CancellablePromise<$models.ScheduleDTO>}
 */
export function GetPauseSchedule() {
    return $Call.ByID(3662115662).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetSetupInfo returns account + storage details for the setup screen.
 * @returns {$CancellablePromise<$models.SetupInfo>}
 */
export function GetSetupInfo() {
    return $Call.ByID(4057305580).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetSyncMode returns "live" (default) or "ondemand".
 * @returns {$CancellablePromise<string>}
 */
export function GetSyncMode() {
    return $Call.ByID(4244864795);
}

/**
 * GetTheme returns the UI theme mode: "system" (default), "light", or "dark".
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(1815524992);
}

/**
 * Header returns the account name, Nextcloud presence and storage quota for the
 * flyout header.
 * @returns {$CancellablePromise<$models.HeaderInfo>}
 */
export function Header() {
    return $Call.ByID(3679066424).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * InitialStatusTab returns (and clears) the tab the status window should open
 * on; the status view calls it once on mount. "" means the default tab.
 * @returns {$CancellablePromise<string>}
 */
export function InitialStatusTab() {
    return $Call.ByID(201191764);
}

/**
 * LicenceInfo reports the current licence state for the Settings UI.
 * @returns {$CancellablePromise<license$0.Info>}
 */
export function LicenceInfo() {
    return $Call.ByID(2163230976).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * ListAccounts returns every configured account. All of them sync
 * concurrently; Active marks the primary one the windows and flyout show.
 * @returns {$CancellablePromise<$models.AccountEntryDTO[]>}
 */
export function ListAccounts() {
    return $Call.ByID(2919187697).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * LogPath returns the application log file path.
 * @returns {$CancellablePromise<string>}
 */
export function LogPath() {
    return $Call.ByID(3838167666);
}

/**
 * LowMemoryMode reports whether the baseline is read from disk per sync (small
 * footprint) rather than held resident in RAM (faster warm syncs). Default true.
 * @returns {$CancellablePromise<boolean>}
 */
export function LowMemoryMode() {
    return $Call.ByID(712472729);
}

/**
 * MoveSyncFolder re-points the sync folder at oldLocal to newLocal WITHOUT
 * re-downloading. If newLocal already holds the content (the user moved it in
 * Explorer / restored a backup) it just re-keys the sync state; otherwise it
 * relocates the folder there first — an instant rename on the same drive, or a
 * recursive copy-then-delete across drives. Returns "" on success, else a
 * human-readable error.
 * @param {string} oldLocal
 * @param {string} newLocal
 * @returns {$CancellablePromise<string>}
 */
export function MoveSyncFolder(oldLocal, newLocal) {
    return $Call.ByID(2122683691, oldLocal, newLocal);
}

/**
 * NeedsLogin reports whether no account is configured yet.
 * @returns {$CancellablePromise<boolean>}
 */
export function NeedsLogin() {
    return $Call.ByID(3546241639);
}

/**
 * NextcloudAppearance reports the user's Nextcloud appearance: "dark", "light",
 * or "default" (they follow the system). Returns "" if it can't be determined
 * (engine not ready / network error). Used by the "Match Nextcloud theme" mode.
 * @returns {$CancellablePromise<string>}
 */
export function NextcloudAppearance() {
    return $Call.ByID(2118200819);
}

/**
 * NotificationCount returns the number of pending Nextcloud notifications, for
 * the flyout's notification-bell badge.
 * @returns {$CancellablePromise<number>}
 */
export function NotificationCount() {
    return $Call.ByID(2816866493);
}

/**
 * NotificationList returns the current notifications.
 * @returns {$CancellablePromise<$models.NotifItem[]>}
 */
export function NotificationList() {
    return $Call.ByID(2567004906).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * NotificationsEnabled reports whether desktop toasts are turned on.
 * @returns {$CancellablePromise<boolean>}
 */
export function NotificationsEnabled() {
    return $Call.ByID(2345418796);
}

/**
 * OnDemandSupported reports whether on-demand files can be configured here.
 * @returns {$CancellablePromise<boolean>}
 */
export function OnDemandSupported() {
    return $Call.ByID(3820698327);
}

/**
 * OpenFolder opens a local folder in the OS file manager.
 * @param {string} localDir
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolder(localDir) {
    return $Call.ByID(3894305329, localDir);
}

/**
 * OpenLogFolder reveals the log directory in the file manager.
 * @returns {$CancellablePromise<void>}
 */
export function OpenLogFolder() {
    return $Call.ByID(4243760357);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenLogs() {
    return $Call.ByID(1517045594);
}

/**
 * OpenSettings opens (or focuses) the sync-settings window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(2024983644);
}

/**
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function OpenShare(remotePath) {
    return $Call.ByID(1062225524, remotePath);
}

/**
 * OpenStatus opens (or focuses) the status window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenStatus() {
    return $Call.ByID(1604289779);
}

/**
 * OpenStatusTab opens (or focuses) the status window on a specific tab
 * ("activity", "conflicts", "notifications", "blocked", "trash").
 * @param {string} tab
 * @returns {$CancellablePromise<void>}
 */
export function OpenStatusTab(tab) {
    return $Call.ByID(2828407018, tab);
}

/**
 * OpenSyncFolder opens the account's sync folder (base dir) in Explorer.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSyncFolder() {
    return $Call.ByID(462717982);
}

/**
 * OpenURL opens a link in the default browser.
 * @param {string} href
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(href) {
    return $Call.ByID(3584934946, href);
}

/**
 * OpenVersions opens (or focuses) the version-history window for a remote,
 * files-root-relative path.
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function OpenVersions(remotePath) {
    return $Call.ByID(2761889176, remotePath);
}

/**
 * OtherAccountAttention lists background accounts that need attention.
 * @returns {$CancellablePromise<$models.OtherAttention[]>}
 */
export function OtherAccountAttention() {
    return $Call.ByID(3107861882).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * PauseFor pauses syncing for the given minutes (0 = indefinitely).
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function PauseFor(minutes) {
    return $Call.ByID(643734224, minutes);
}

/**
 * PauseInfo returns the current pause state.
 * @returns {$CancellablePromise<$models.PauseDTO>}
 */
export function PauseInfo() {
    return $Call.ByID(3615706181).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * PauseUntilTomorrow pauses until 08:00 the next day.
 * @returns {$CancellablePromise<void>}
 */
export function PauseUntilTomorrow() {
    return $Call.ByID(646879136);
}

/**
 * Paused reports whether syncing is paused.
 * @returns {$CancellablePromise<boolean>}
 */
export function Paused() {
    return $Call.ByID(2392889939);
}

/**
 * PickLocalFolder opens a native folder picker and returns the chosen path (or
 * "" if cancelled). start seeds the initial directory.
 * @param {string} start
 * @returns {$CancellablePromise<string>}
 */
export function PickLocalFolder(start) {
    return $Call.ByID(2236559743, start);
}

/**
 * PinApp / UnpinApp toggle an app's pinned state.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function PinApp(id) {
    return $Call.ByID(3884739535, id);
}

/**
 * PolicyInfo reports the active admin policy for the Settings UI.
 * @returns {$CancellablePromise<$models.PolicyDTO>}
 */
export function PolicyInfo() {
    return $Call.ByID(4136447139).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * Progress returns the current sync-progress snapshot.
 * @returns {$CancellablePromise<$models.ProgressDTO>}
 */
export function Progress() {
    return $Call.ByID(1801045022).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * Quit exits the application.
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3181047470);
}

/**
 * RecentActivity returns the recent sync operations (newest first) across ALL
 * syncing accounts, each item tagged with its account when more than one is
 * configured.
 * @returns {$CancellablePromise<$models.ActivityItem[]>}
 */
export function RecentActivity() {
    return $Call.ByID(3561310187).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * RemoveAccount disconnects a NON-active account: its keychain secret, account
 * entry, sync-folder setup and local sync state are removed (local files are
 * kept). Removing the active account is SignOut's job — it handles the engine
 * teardown and next-account handover.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function RemoveAccount(id) {
    return $Call.ByID(205763644, id);
}

/**
 * @param {string} localDir
 * @param {string} rel
 * @returns {$CancellablePromise<void>}
 */
export function RemoveExclude(localDir, rel) {
    return $Call.ByID(1972269193, localDir, rel);
}

/**
 * RemoveLicence deletes the installed business licence (back to free personal).
 * @returns {$CancellablePromise<string>}
 */
export function RemoveLicence() {
    return $Call.ByID(3780167700);
}

/**
 * @param {string} remotePath
 * @param {boolean} deleteLocal
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSyncFolder(remotePath, deleteLocal) {
    return $Call.ByID(2181427266, remotePath, deleteLocal);
}

/**
 * RenameBlocked renames a blocked file so it can sync.
 * @param {string} abs
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameBlocked(abs, newName) {
    return $Call.ByID(3581123109, abs, newName);
}

/**
 * OpenLogs opens (or focuses) the in-app log viewer window.
 * ReportProblem bundles everything a bug report needs — the log files, a
 * diagnostics snapshot, the version, and the (secret-free) settings — into a
 * zip in Downloads, reveals it in Explorer, and opens the GitHub new-issue
 * page so the user can attach it. Returns "" on success or an error message.
 * No data leaves the machine until the user themselves attaches the file.
 * @returns {$CancellablePromise<string>}
 */
export function ReportProblem() {
    return $Call.ByID(4140541026);
}

/**
 * ResolveConflict settles a conflict: choice is "local", "remote", or "both".
 * @param {string} localDir
 * @param {string} path
 * @param {string} choice
 * @returns {$CancellablePromise<void>}
 */
export function ResolveConflict(localDir, path, choice) {
    return $Call.ByID(1946249505, localDir, path, choice);
}

/**
 * RestoreTrash restores a trashed item by href. Returns "" on success.
 * @param {string} href
 * @returns {$CancellablePromise<string>}
 */
export function RestoreTrash(href) {
    return $Call.ByID(1323775737, href);
}

/**
 * RestoreVersion makes a stored version current. Returns "" on success.
 * @param {string} href
 * @returns {$CancellablePromise<string>}
 */
export function RestoreVersion(href) {
    return $Call.ByID(1999196387, href);
}

/**
 * Resume clears any pause (manual or timed).
 * @returns {$CancellablePromise<void>}
 */
export function Resume() {
    return $Call.ByID(2476070530);
}

/**
 * Search queries Nextcloud's unified file search for term (for the flyout).
 * @param {string} term
 * @returns {$CancellablePromise<$models.SearchItem[]>}
 */
export function Search(term) {
    return $Call.ByID(3097496321, term).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * SetAllowedFilenames persists the allow-list (trimmed, de-duped). It takes
 * effect on the next launch, since the forbidden-name matcher is built when the
 * engine connects to the server.
 * @param {string[]} names
 * @returns {$CancellablePromise<void>}
 */
export function SetAllowedFilenames(names) {
    return $Call.ByID(1878895897, names);
}

/**
 * SetAppDockSide persists the dock edge ("left", "right", or "bottom") and
 * broadcasts it so the flyout moves the rail live.
 * @param {string} side
 * @returns {$CancellablePromise<void>}
 */
export function SetAppDockSide(side) {
    return $Call.ByID(2454065770, side);
}

/**
 * @param {boolean} on
 * @returns {$CancellablePromise<string>}
 */
export function SetAutostart(on) {
    return $Call.ByID(1324798748, on);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetBaseDir(dir) {
    return $Call.ByID(1736883101, dir);
}

/**
 * SetConflictPolicy saves and applies the default conflict policy.
 * @param {string} policy
 * @returns {$CancellablePromise<void>}
 */
export function SetConflictPolicy(policy) {
    return $Call.ByID(2608990779, policy);
}

/**
 * SetFlyoutAppearance persists the flyout appearance, resizes the panel, and
 * broadcasts so an open flyout updates live.
 * @param {$models.FlyoutAppearanceDTO} dto
 * @returns {$CancellablePromise<void>}
 */
export function SetFlyoutAppearance(dto) {
    return $Call.ByID(1305195766, dto);
}

/**
 * @param {string[]} patterns
 * @returns {$CancellablePromise<void>}
 */
export function SetIgnore(patterns) {
    return $Call.ByID(2741577297, patterns);
}

/**
 * SetIgnorePatterns persists the global ignore patterns (trimmed, comments/blank
 * lines dropped) and triggers a sync so the change applies promptly. Ignored
 * paths are left untouched on both sides (not synced, not deleted).
 * @param {string[]} patterns
 * @returns {$CancellablePromise<void>}
 */
export function SetIgnorePatterns(patterns) {
    return $Call.ByID(3670226026, patterns);
}

/**
 * @param {number} up
 * @param {number} down
 * @returns {$CancellablePromise<void>}
 */
export function SetLimits(up, down) {
    return $Call.ByID(1735591375, up, down);
}

/**
 * SetLowMemoryMode toggles the resident-baseline cache and reopens the store so it
 * takes effect immediately (freeing the cache when turning low-memory on).
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetLowMemoryMode(on) {
    return $Call.ByID(235687351, on);
}

/**
 * SetNotifications turns desktop toasts on or off and persists the choice.
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetNotifications(on) {
    return $Call.ByID(3799093, on);
}

/**
 * SetOfflinePin pins (always keep on this device — fully downloads and stays
 * current) or unpins (back to online-only preference) a folder subtree in the
 * shown account's virtual root.
 * @param {string} rel
 * @param {boolean} pinned
 * @returns {$CancellablePromise<string>}
 */
export function SetOfflinePin(rel, pinned) {
    return $Call.ByID(2108331737, rel, pinned);
}

/**
 * SetPauseSchedule saves and applies the quiet-hours window.
 * @param {boolean} enabled
 * @param {number} fromMin
 * @param {number} toMin
 * @returns {$CancellablePromise<void>}
 */
export function SetPauseSchedule(enabled, fromMin, toMin) {
    return $Call.ByID(1511172154, enabled, fromMin, toMin);
}

/**
 * SetShellMenu registers or removes the Explorer "Share with Nimbo" entry.
 * @param {boolean} on
 * @returns {$CancellablePromise<string>}
 */
export function SetShellMenu(on) {
    return $Call.ByID(1337506016, on);
}

/**
 * SetShowAppDock persists whether the app dock is shown and broadcasts it so the
 * flyout updates live.
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetShowAppDock(on) {
    return $Call.ByID(1564154138, on);
}

/**
 * SetShowSearch persists whether the search bar is shown and broadcasts it so
 * the flyout updates live.
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetShowSearch(on) {
    return $Call.ByID(2026753822, on);
}

/**
 * SetSidebar adds or removes the Nimbo root in the Explorer navigation
 * pane, pointing at the default sync location.
 * @param {boolean} on
 * @returns {$CancellablePromise<string>}
 */
export function SetSidebar(on) {
    return $Call.ByID(1812248757, on);
}

/**
 * SetStatusMessage sets a custom status message.
 * @param {string} msg
 * @returns {$CancellablePromise<void>}
 */
export function SetStatusMessage(msg) {
    return $Call.ByID(2091248908, msg);
}

/**
 * SetStatusType sets the user's Nextcloud presence (online/away/dnd/invisible).
 * @param {string} t
 * @returns {$CancellablePromise<void>}
 */
export function SetStatusType(t) {
    return $Call.ByID(914128197, t);
}

/**
 * SetSyncMode switches the account between "live" and "ondemand". On-demand
 * clears any live sync pairs (the Cloud Files provider owns the files; an
 * overlapping pair would fight the placeholder watcher) and mounts the account
 * folder. Switching back to live unmounts it. Local files are left in place.
 * @param {string} mode
 * @returns {$CancellablePromise<string>}
 */
export function SetSyncMode(mode) {
    return $Call.ByID(29183279, mode);
}

/**
 * SetTheme persists the UI theme mode and broadcasts it so every window updates.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(mode) {
    return $Call.ByID(3669652676, mode);
}

/**
 * SetVerbose turns debug logging on/off (live) and persists the choice.
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetVerbose(on) {
    return $Call.ByID(2881567667, on);
}

/**
 * ShareList returns the existing shares on the target path.
 * @returns {$CancellablePromise<$models.ShareDTO[]>}
 */
export function ShareList() {
    return $Call.ByID(427148648).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * ShareTarget returns the path the share window is acting on.
 * @returns {$CancellablePromise<string>}
 */
export function ShareTarget() {
    return $Call.ByID(4168581225);
}

/**
 * ShellMenuEnabled reports whether the Explorer "Share" entry is registered.
 * @returns {$CancellablePromise<boolean>}
 */
export function ShellMenuEnabled() {
    return $Call.ByID(2447081083);
}

/**
 * ShellMenuSupported reports whether the Explorer integration is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function ShellMenuSupported() {
    return $Call.ByID(365944660);
}

/**
 * ShowAppDock reports whether the flyout's right-side app dock is shown
 * (default true).
 * @returns {$CancellablePromise<boolean>}
 */
export function ShowAppDock() {
    return $Call.ByID(1827415032);
}

/**
 * ShowSearch reports whether the flyout's file-search bar is shown (default
 * true).
 * @returns {$CancellablePromise<boolean>}
 */
export function ShowSearch() {
    return $Call.ByID(3242052312);
}

/**
 * SidebarEnabled reports whether the Nimbo sidebar root is registered.
 * @returns {$CancellablePromise<boolean>}
 */
export function SidebarEnabled() {
    return $Call.ByID(4033118708);
}

/**
 * SidebarSupported reports whether the Explorer sidebar entry is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function SidebarSupported() {
    return $Call.ByID(2636282971);
}

/**
 * SignOut forgets the account (store + keychain), tears down syncing and any
 * on-demand mount, closes the signed-in windows, and shows the sign-in window —
 * a clean reset to the not-signed-in state. Local files are left untouched.
 * (A full process restart is unreliable for a packaged app: the OS job object
 * kills any relauncher when we exit, so we reset in place instead.)
 * SignOut disconnects the account. With clearData false it's a temporary
 * sign-out — the synced-folder setup and local sync database are kept for a
 * quick re-login. With clearData true they're wiped too, for a clean reset (and
 * so a fresh login can't mistake a since-deleted local folder for user deletions
 * and propagate them to the server). UI preferences are kept either way.
 * @param {boolean} clearData
 * @returns {$CancellablePromise<string>}
 */
export function SignOut(clearData) {
    return $Call.ByID(578162832, clearData);
}

/**
 * Status returns the current sync status text.
 * @returns {$CancellablePromise<string>}
 */
export function Status() {
    return $Call.ByID(2836613335);
}

/**
 * SwitchAccount makes the given account the primary one — the account the
 * windows, flyout and folder settings show. ALL configured accounts keep
 * syncing regardless (the previous primary continues as a background
 * secondary); each keeps its own sync folders, state database, and caches.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function SwitchAccount(id) {
    return $Call.ByID(3396723464, id);
}

/**
 * SyncNow triggers an immediate sync of all folders.
 * @returns {$CancellablePromise<void>}
 */
export function SyncNow() {
    return $Call.ByID(2954670258);
}

/**
 * SyncedRemotes returns the remote paths currently configured as sync pairs.
 * @returns {$CancellablePromise<string[]>}
 */
export function SyncedRemotes() {
    return $Call.ByID(1824770878).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * TailLog returns the last ~64 KB of the log file for the in-app viewer.
 * @returns {$CancellablePromise<string>}
 */
export function TailLog() {
    return $Call.ByID(614378587);
}

/**
 * ThemeColor returns the user's Nextcloud primary theme colour (hex) to accent
 * the UI, or "" to use the default.
 * @returns {$CancellablePromise<string>}
 */
export function ThemeColor() {
    return $Call.ByID(2514990749);
}

/**
 * TogglePause flips the paused state and returns the new value.
 * @returns {$CancellablePromise<boolean>}
 */
export function TogglePause() {
    return $Call.ByID(564640869);
}

/**
 * TrashList returns the items currently in the trashbin.
 * @returns {$CancellablePromise<$models.TrashDTO[]>}
 */
export function TrashList() {
    return $Call.ByID(2716350569).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function UnpinApp(id) {
    return $Call.ByID(2596640760, id);
}

/**
 * Verbose reports whether debug logging is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function Verbose() {
    return $Call.ByID(2262807045);
}

/**
 * Version returns the application build version.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(2431199839);
}

/**
 * VersionList returns the version history of the version-window's target file.
 * @returns {$CancellablePromise<$models.VersionDTO[]>}
 */
export function VersionList() {
    return $Call.ByID(3868762695).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * VersionTarget returns the path the version window is acting on.
 * @returns {$CancellablePromise<string>}
 */
export function VersionTarget() {
    return $Call.ByID(2489279714);
}

// Private type creation functions
const $$createType0 = $models.AccountDTO.createFrom;
const $$createType1 = $models.AppInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.AttentionInfo.createFrom;
const $$createType4 = $models.BlockedItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.BrandDTO.createFrom;
const $$createType7 = $models.OfflineEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.BrowseEntry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.UpdateDTO.createFrom;
const $$createType12 = $models.ConflictPreview.createFrom;
const $$createType13 = $models.ConflictItem.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.DiagnosticsDTO.createFrom;
const $$createType16 = $models.FlyoutAppearanceDTO.createFrom;
const $$createType17 = $models.FolderInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($Create.Any);
const $$createType20 = $models.LimitsDTO.createFrom;
const $$createType21 = $models.PairDTO.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $models.ScheduleDTO.createFrom;
const $$createType24 = $models.SetupInfo.createFrom;
const $$createType25 = $models.HeaderInfo.createFrom;
const $$createType26 = license$0.Info.createFrom;
const $$createType27 = $models.AccountEntryDTO.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $models.NotifItem.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = $models.OtherAttention.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $models.PauseDTO.createFrom;
const $$createType34 = $models.PolicyDTO.createFrom;
const $$createType35 = $models.ProgressDTO.createFrom;
const $$createType36 = $models.ActivityItem.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = $models.SearchItem.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = $models.ShareDTO.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = $models.TrashDTO.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = $models.VersionDTO.createFrom;
const $$createType45 = $Create.Array($$createType44);
