// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccountDTO describes the signed-in account for the settings UI.
 */
export class AccountDTO {
    /**
     * Creates a new AccountDTO instance.
     * @param {Partial<AccountDTO>} [$$source = {}] - The source object to create the AccountDTO.
     */
    constructor($$source = {}) {
        if (!("signedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["signedIn"] = false;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("localAddress" in $$source)) {
            /**
             * Local network route (spec 2026-09-13): the saved address as the user
             * typed it, and whether its certificate is pinned. Live route state is on
             * DiagnosticsDTO, which Settings already polls.
             * @member
             * @type {string}
             */
            this["localAddress"] = "";
        }
        if (!("localPinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["localPinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountDTO(/** @type {Partial<AccountDTO>} */($$parsedSource));
    }
}

/**
 * AccountEntryDTO is one configured account in the account list.
 */
export class AccountEntryDTO {
    /**
     * Creates a new AccountEntryDTO instance.
     * @param {Partial<AccountEntryDTO>} [$$source = {}] - The source object to create the AccountEntryDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * latest engine status line ("" if not running)
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("route" in $$source)) {
            /**
             * "local" while syncing over the local network, else "public"
             * @member
             * @type {string}
             */
            this["route"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountEntryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountEntryDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountEntryDTO(/** @type {Partial<AccountEntryDTO>} */($$parsedSource));
    }
}

/**
 * ActivityItem is one recent sync operation.
 */
export class ActivityItem {
    /**
     * Creates a new ActivityItem instance.
     * @param {Partial<ActivityItem>} [$$source = {}] - The source object to create the ActivityItem.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * pair-relative path
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("remotePath" in $$source)) {
            /**
             * files-root-relative path (for sharing)
             * @member
             * @type {string}
             */
            this["remotePath"] = "";
        }
        if (!("localPath" in $$source)) {
            /**
             * absolute local path (for "show in folder"); "" when the event has no owning folder
             * @member
             * @type {string}
             */
            this["localPath"] = "";
        }
        if (!("err" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["err"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * owning account's user name (set when several accounts are configured)
             * @member
             * @type {string}
             */
            this["account"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActivityItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivityItem(/** @type {Partial<ActivityItem>} */($$parsedSource));
    }
}

/**
 * AppInfo is a Nextcloud app for the flyout (with its pinned state).
 * Shortcut reports a Start-menu shortcut for the app (Windows). NOTE: the field
 * reaches the frontend through the generated bindings WITHOUT a regen — the
 * model constructor's Object.assign passes unknown JSON fields through — so
 * keep it additive and read it untyped ((a as any).shortcut) in Svelte.
 */
export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("href" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["href"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("shortcut" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["shortcut"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}

/**
 * AttentionInfo counts items needing the user's attention.
 */
export class AttentionInfo {
    /**
     * Creates a new AttentionInfo instance.
     * @param {Partial<AttentionInfo>} [$$source = {}] - The source object to create the AttentionInfo.
     */
    constructor($$source = {}) {
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (!("blocked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["blocked"] = 0;
        }
        if (!("locked" in $$source)) {
            /**
             * Locked: files someone else has open. Informational, not a fault — the UI
             * wording should reflect that.
             * @member
             * @type {number}
             */
            this["locked"] = 0;
        }
        if (!("detached" in $$source)) {
            /**
             * Detached: folders that stopped being shared with the user (or whose
             * storage was unmounted) and whose kept local copy awaits a decision.
             * @member
             * @type {number}
             */
            this["detached"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttentionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AttentionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttentionInfo(/** @type {Partial<AttentionInfo>} */($$parsedSource));
    }
}

/**
 * BlockedItem is a file that can't sync (server-forbidden name), or — when
 * Escaping is set — a synthetic row for an extension currently being escaped
 * (its "Ext" is what a "stop escaping" action removes).
 */
export class BlockedItem {
    /**
     * Creates a new BlockedItem instance.
     * @param {Partial<BlockedItem>} [$$source = {}] - The source object to create the BlockedItem.
     */
    constructor($$source = {}) {
        if (!("abs" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["abs"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("ext" in $$source)) {
            /**
             * file extension (for the escape opt-in label)
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("escapable" in $$source)) {
            /**
             * opting Ext in would let this file sync
             * @member
             * @type {boolean}
             */
            this["escapable"] = false;
        }
        if (!("escaping" in $$source)) {
            /**
             * synthetic row: this Ext is currently escaped
             * @member
             * @type {boolean}
             */
            this["escaping"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockedItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlockedItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlockedItem(/** @type {Partial<BlockedItem>} */($$parsedSource));
    }
}

/**
 * BrandDTO carries the white-labellable identity values the frontend shows.
 */
export class BrandDTO {
    /**
     * Creates a new BrandDTO instance.
     * @param {Partial<BrandDTO>} [$$source = {}] - The source object to create the BrandDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("company" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["company"] = "";
        }
        if (!("website" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["website"] = "";
        }
        if (!("support" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["support"] = "";
        }
        if (!("help" in $$source)) {
            /**
             * help home, "" when the brand has none
             * @member
             * @type {string}
             */
            this["help"] = "";
        }
        if (!("accentHex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accentHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrandDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrandDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrandDTO(/** @type {Partial<BrandDTO>} */($$parsedSource));
    }
}

/**
 * BrowseEntry is a remote folder/file for the folder picker.
 */
export class BrowseEntry {
    /**
     * Creates a new BrowseEntry instance.
     * @param {Partial<BrowseEntry>} [$$source = {}] - The source object to create the BrowseEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowseEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowseEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowseEntry(/** @type {Partial<BrowseEntry>} */($$parsedSource));
    }
}

/**
 * ConflictItem is a pending conflict awaiting a choice, with both versions'
 * size and modified time so the user can decide.
 */
export class ConflictItem {
    /**
     * Creates a new ConflictItem instance.
     * @param {Partial<ConflictItem>} [$$source = {}] - The source object to create the ConflictItem.
     */
    constructor($$source = {}) {
        if (!("localDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("localExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["localExists"] = false;
        }
        if (!("remoteExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["remoteExists"] = false;
        }
        if (!("localSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localSize"] = 0;
        }
        if (!("localMTime" in $$source)) {
            /**
             * "YYYY-MM-DD HH:MM" or ""
             * @member
             * @type {string}
             */
            this["localMTime"] = "";
        }
        if (!("remoteSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remoteSize"] = 0;
        }
        if (!("remoteMTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteMTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictItem(/** @type {Partial<ConflictItem>} */($$parsedSource));
    }
}

/**
 * ConflictPreview holds both versions' content previews so the user can see what
 * they're choosing between, not just sizes and timestamps.
 */
export class ConflictPreview {
    /**
     * Creates a new ConflictPreview instance.
     * @param {Partial<ConflictPreview>} [$$source = {}] - The source object to create the ConflictPreview.
     */
    constructor($$source = {}) {
        if (!("local" in $$source)) {
            /**
             * @member
             * @type {SidePreview}
             */
            this["local"] = (new SidePreview());
        }
        if (!("remote" in $$source)) {
            /**
             * @member
             * @type {SidePreview}
             */
            this["remote"] = (new SidePreview());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictPreview}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local" in $$parsedSource) {
            $$parsedSource["local"] = $$createField0_0($$parsedSource["local"]);
        }
        if ("remote" in $$parsedSource) {
            $$parsedSource["remote"] = $$createField1_0($$parsedSource["remote"]);
        }
        return new ConflictPreview(/** @type {Partial<ConflictPreview>} */($$parsedSource));
    }
}

/**
 * DetachedDTO is a folder that stopped being shared with the user (or whose
 * storage was unmounted) and whose kept local copy is waiting for a decision.
 */
export class DetachedDTO {
    /**
     * Creates a new DetachedDTO instance.
     * @param {Partial<DetachedDTO>} [$$source = {}] - The source object to create the DetachedDTO.
     */
    constructor($$source = {}) {
        if (!("localDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }
        if (!("rel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rel"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("localPath" in $$source)) {
            /**
             * where the copy is — the key ResolveDetached takes
             * @member
             * @type {string}
             */
            this["localPath"] = "";
        }
        if (!("movedOut" in $$source)) {
            /**
             * parked beside the sync folder (on-demand), not inside it
             * @member
             * @type {boolean}
             */
            this["movedOut"] = false;
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetachedDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetachedDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetachedDTO(/** @type {Partial<DetachedDTO>} */($$parsedSource));
    }
}

/**
 * DiagnosticsDTO is a connection/sync health snapshot for the health panel.
 */
export class DiagnosticsDTO {
    /**
     * Creates a new DiagnosticsDTO instance.
     * @param {Partial<DiagnosticsDTO>} [$$source = {}] - The source object to create the DiagnosticsDTO.
     */
    constructor($$source = {}) {
        if (!("serverURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverURL"] = "";
        }
        if (!("serverVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverVersion"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account"] = "";
        }
        if (!("pushAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pushAvailable"] = false;
        }
        if (!("pushConnected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pushConnected"] = false;
        }
        if (!("pushUptime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pushUptime"] = "";
        }
        if (!("lastStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastStatus"] = "";
        }
        if (!("lastSync" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSync"] = "";
        }
        if (!("adoptScanDirs" in $$source)) {
            /**
             * AdoptScanDirs is the adopt scan's live heartbeat: directories listed so
             * far, 0 when no scan is running. Rides this already-polled DTO so the
             * scanning overlay gets a moving number without a new binding.
             * @member
             * @type {number}
             */
            this["adoptScanDirs"] = 0;
        }
        if (!("adoptConvertDone" in $$source)) {
            /**
             * AdoptConvertDone/Total is the background conversion's heartbeat (files
             * marked so far / plan size); Total 0 = no conversion running.
             * @member
             * @type {number}
             */
            this["adoptConvertDone"] = 0;
        }
        if (!("adoptConvertTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["adoptConvertTotal"] = 0;
        }
        if (!("revertDone" in $$source)) {
            /**
             * RevertDone/Total: the leave-VFS pass, same shape.
             * @member
             * @type {number}
             */
            this["revertDone"] = 0;
        }
        if (!("revertTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revertTotal"] = 0;
        }
        if (!("escapeExtensions" in $$source)) {
            /**
             * EscapeExtensions: file types currently synced under disguised names
             * (server-forbidden names only). Rides here so the Exclusions UI can list
             * them without a new binding.
             * @member
             * @type {string[]}
             */
            this["escapeExtensions"] = [];
        }
        if (!("lockingAvailable" in $$source)) {
            /**
             * LockingAvailable: the server has the files_lock app. When false the UI must
             * say it CANNOT KNOW who has a file open — "nobody has this open" would be a
             * different and untrue claim. Rides here rather than adding a binding.
             * @member
             * @type {boolean}
             */
            this["lockingAvailable"] = false;
        }
        if (!("observedLocks" in $$source)) {
            /**
             * ObservedLocks: files other users currently have open, across every account.
             * @member
             * @type {LockDTO[]}
             */
            this["observedLocks"] = [];
        }
        if (!("fileLocking" in $$source)) {
            /**
             * FileLocking: whether Nimbo takes locks of its own (off by default).
             * @member
             * @type {boolean}
             */
            this["fileLocking"] = false;
        }
        if (!("fileLockout" in $$source)) {
            /**
             * FileLockout: whether Nimbo also holds other people's locked files open
             * locally, so the editor here refuses them (off by default).
             * @member
             * @type {boolean}
             */
            this["fileLockout"] = false;
        }
        if (!("badgesRegistered" in $$source)) {
            /**
             * BadgesRegistered: the current generation of Explorer corner badges is
             * registered on this machine (badges.go). When false in live mode, the UI
             * offers the one-UAC enable step.
             * @member
             * @type {boolean}
             */
            this["badgesRegistered"] = false;
        }
        if (!("heldLocks" in $$source)) {
            /**
             * HeldLocks: locks NIMBO holds, across every account. Surfaced so the user can
             * see and clear them — the server will never expire one on its own.
             * @member
             * @type {LockDTO[]}
             */
            this["heldLocks"] = [];
        }
        if (!("route" in $$source)) {
            /**
             * Local network route (spec 2026-09-13).
             * "local" | "public"
             * @member
             * @type {string}
             */
            this["route"] = "";
        }
        if (!("routeReason" in $$source)) {
            /**
             * why public, when a local address is set
             * @member
             * @type {string}
             */
            this["routeReason"] = "";
        }
        if (!("localAddress" in $$source)) {
            /**
             * configured dial target, "" = none
             * @member
             * @type {string}
             */
            this["localAddress"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticsDTO}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType1;
        const $$createField15_0 = $$createType3;
        const $$createField19_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("escapeExtensions" in $$parsedSource) {
            $$parsedSource["escapeExtensions"] = $$createField13_0($$parsedSource["escapeExtensions"]);
        }
        if ("observedLocks" in $$parsedSource) {
            $$parsedSource["observedLocks"] = $$createField15_0($$parsedSource["observedLocks"]);
        }
        if ("heldLocks" in $$parsedSource) {
            $$parsedSource["heldLocks"] = $$createField19_0($$parsedSource["heldLocks"]);
        }
        return new DiagnosticsDTO(/** @type {Partial<DiagnosticsDTO>} */($$parsedSource));
    }
}

/**
 * FlyoutAppearanceDTO carries the flyout's appearance settings to the UI.
 */
export class FlyoutAppearanceDTO {
    /**
     * Creates a new FlyoutAppearanceDTO instance.
     * @param {Partial<FlyoutAppearanceDTO>} [$$source = {}] - The source object to create the FlyoutAppearanceDTO.
     */
    constructor($$source = {}) {
        if (!("dockIconSize" in $$source)) {
            /**
             * small | medium | large
             * @member
             * @type {string}
             */
            this["dockIconSize"] = "";
        }
        if (!("panelWidth" in $$source)) {
            /**
             * compact | standard | wide
             * @member
             * @type {string}
             */
            this["panelWidth"] = "";
        }
        if (!("density" in $$source)) {
            /**
             * comfortable | compact
             * @member
             * @type {string}
             */
            this["density"] = "";
        }
        if (!("sections" in $$source)) {
            /**
             * ordered visible middle sections
             * @member
             * @type {string[]}
             */
            this["sections"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlyoutAppearanceDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FlyoutAppearanceDTO}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sections" in $$parsedSource) {
            $$parsedSource["sections"] = $$createField3_0($$parsedSource["sections"]);
        }
        return new FlyoutAppearanceDTO(/** @type {Partial<FlyoutAppearanceDTO>} */($$parsedSource));
    }
}

/**
 * FolderInfo is a synced folder for the flyout's quick buttons.
 */
export class FolderInfo {
    /**
     * Creates a new FolderInfo instance.
     * @param {Partial<FolderInfo>} [$$source = {}] - The source object to create the FolderInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("localDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderInfo(/** @type {Partial<FolderInfo>} */($$parsedSource));
    }
}

/**
 * HeaderInfo describes the signed-in user and their Nextcloud presence.
 */
export class HeaderInfo {
    /**
     * Creates a new HeaderInfo instance.
     * @param {Partial<HeaderInfo>} [$$source = {}] - The source object to create the HeaderInfo.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("statusType" in $$source)) {
            /**
             * online | away | dnd | invisible | offline
             * @member
             * @type {string}
             */
            this["statusType"] = "";
        }
        if (!("statusMsg" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusMsg"] = "";
        }
        if (!("statusIcon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusIcon"] = "";
        }
        if (!("quotaUsed" in $$source)) {
            /**
             * bytes used
             * @member
             * @type {number}
             */
            this["quotaUsed"] = 0;
        }
        if (!("quotaTotal" in $$source)) {
            /**
             * effective total bytes (0 if unknown)
             * @member
             * @type {number}
             */
            this["quotaTotal"] = 0;
        }
        if (!("quotaPct" in $$source)) {
            /**
             * percent used (0–100)
             * @member
             * @type {number}
             */
            this["quotaPct"] = 0;
        }
        if (!("unlimited" in $$source)) {
            /**
             * no configured quota
             * @member
             * @type {boolean}
             */
            this["unlimited"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeaderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HeaderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeaderInfo(/** @type {Partial<HeaderInfo>} */($$parsedSource));
    }
}

/**
 * LimitsDTO is the bandwidth configuration (KiB/s; 0 = unlimited).
 */
export class LimitsDTO {
    /**
     * Creates a new LimitsDTO instance.
     * @param {Partial<LimitsDTO>} [$$source = {}] - The source object to create the LimitsDTO.
     */
    constructor($$source = {}) {
        if (!("up" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["up"] = 0;
        }
        if (!("down" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["down"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LimitsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LimitsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LimitsDTO(/** @type {Partial<LimitsDTO>} */($$parsedSource));
    }
}

/**
 * LocalTestDTO is the outcome of TestLocalAddress. Result is one of "ok",
 * "invalid", "unreachable", "not-https", "not-nextcloud", "untrusted",
 * "different-server", "error"; Message is user-facing. The certificate fields
 * are filled for "untrusted" (the trust dialog) and "ok". Address is the
 * canonical form of what was typed — Save stores that.
 */
export class LocalTestDTO {
    /**
     * Creates a new LocalTestDTO instance.
     * @param {Partial<LocalTestDTO>} [$$source = {}] - The source object to create the LocalTestDTO.
     */
    constructor($$source = {}) {
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["result"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("issuer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["issuer"] = "";
        }
        if (!("expires" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expires"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTestDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalTestDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalTestDTO(/** @type {Partial<LocalTestDTO>} */($$parsedSource));
    }
}

/**
 * LockDTO is one file another user holds open, for the Settings list.
 */
export class LockDTO {
    /**
     * Creates a new LockDTO instance.
     * @param {Partial<LockDTO>} [$$source = {}] - The source object to create the LockDTO.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("owner" in $$source)) {
            /**
             * display name where the server gave one, else the login
             * @member
             * @type {string}
             */
            this["owner"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * ready-made one-liner; an app lock names no person
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("ownerType" in $$source)) {
            /**
             * 0 manual, 1 an app (Text/Office), 2 token
             * @member
             * @type {number}
             */
            this["ownerType"] = 0;
        }
        if (!("since" in $$source)) {
            /**
             * RFC3339; empty when the server gave no time
             * @member
             * @type {string}
             */
            this["since"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * login name of the account it belongs to
             * @member
             * @type {string}
             */
            this["account"] = "";
        }
        if (!("localDir" in $$source)) {
            /**
             * the sync folder it is listed under, for UnlockStaleLock
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }
        if (!("canUnlock" in $$source)) {
            /**
             * a stale lock on a file this account owns (#733)
             * @member
             * @type {boolean}
             */
            this["canUnlock"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LockDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LockDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LockDTO(/** @type {Partial<LockDTO>} */($$parsedSource));
    }
}

/**
 * NotifAction is a button on a notification.
 */
export class NotifAction {
    /**
     * Creates a new NotifAction instance.
     * @param {Partial<NotifAction>} [$$source = {}] - The source object to create the NotifAction.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotifAction}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotifAction(/** @type {Partial<NotifAction>} */($$parsedSource));
    }
}

/**
 * NotifItem is a Nextcloud notification.
 */
export class NotifItem {
    /**
     * Creates a new NotifItem instance.
     * @param {Partial<NotifItem>} [$$source = {}] - The source object to create the NotifItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("app" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {NotifAction[]}
             */
            this["actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotifItem}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField5_0($$parsedSource["actions"]);
        }
        return new NotifItem(/** @type {Partial<NotifItem>} */($$parsedSource));
    }
}

/**
 * OfflineEntry is one folder in the "available offline" browser.
 */
export class OfflineEntry {
    /**
     * Creates a new OfflineEntry instance.
     * @param {Partial<OfflineEntry>} [$$source = {}] - The source object to create the OfflineEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rel"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OfflineEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OfflineEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OfflineEntry(/** @type {Partial<OfflineEntry>} */($$parsedSource));
    }
}

/**
 * OtherAttention reports a background account with pending conflicts or
 * blocked files, so the Status window can point at it.
 */
export class OtherAttention {
    /**
     * Creates a new OtherAttention instance.
     * @param {Partial<OtherAttention>} [$$source = {}] - The source object to create the OtherAttention.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (!("blocked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["blocked"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OtherAttention instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OtherAttention}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OtherAttention(/** @type {Partial<OtherAttention>} */($$parsedSource));
    }
}

/**
 * PairDTO describes a configured sync pair.
 * 
 * The backup fields ride here rather than on a new bound method: DTO fields
 * carry no hashed method ids, so adding them needs no bindings regen (the
 * generated model copies unknown fields straight through).
 */
export class PairDTO {
    /**
     * Creates a new PairDTO instance.
     * @param {Partial<PairDTO>} [$$source = {}] - The source object to create the PairDTO.
     */
    constructor($$source = {}) {
        if (!("localDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }
        if (!("remoteRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteRoot"] = "";
        }
        if (!("excludes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["excludes"] = [];
        }
        if (!("frozen" in $$source)) {
            /**
             * Frozen is true when the damage guard paused this folder pending review.
             * @member
             * @type {boolean}
             */
            this["frozen"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * FreezeReason is the human-readable explanation shown in the banner.
             * @member
             * @type {string | undefined}
             */
            this["freezeReason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * FreezeSample is a few affected paths, so the user can judge the trip.
             * @member
             * @type {string[] | undefined}
             */
            this["freezeSample"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HeldReason says why this folder is not syncing because another account
             * uses it (GitHub #11); "" when it syncs normally.
             * @member
             * @type {string | undefined}
             */
            this["heldReason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PairDTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("excludes" in $$parsedSource) {
            $$parsedSource["excludes"] = $$createField2_0($$parsedSource["excludes"]);
        }
        if ("freezeSample" in $$parsedSource) {
            $$parsedSource["freezeSample"] = $$createField5_0($$parsedSource["freezeSample"]);
        }
        return new PairDTO(/** @type {Partial<PairDTO>} */($$parsedSource));
    }
}

/**
 * PauseDTO mirrors the engine's effective pause state for the UI.
 */
export class PauseDTO {
    /**
     * Creates a new PauseDTO instance.
     * @param {Partial<PauseDTO>} [$$source = {}] - The source object to create the PauseDTO.
     */
    constructor($$source = {}) {
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("until" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["until"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PauseDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PauseDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PauseDTO(/** @type {Partial<PauseDTO>} */($$parsedSource));
    }
}

/**
 * PolicyDTO tells the UI which settings are admin-managed so it can lock them.
 */
export class PolicyDTO {
    /**
     * Creates a new PolicyDTO instance.
     * @param {Partial<PolicyDTO>} [$$source = {}] - The source object to create the PolicyDTO.
     */
    constructor($$source = {}) {
        if (!("managed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["managed"] = false;
        }
        if (!("lockServer" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lockServer"] = false;
        }
        if (!("serverUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverUrl"] = "";
        }
        if (!("allowSignOut" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allowSignOut"] = false;
        }
        if (!("lockBandwidth" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lockBandwidth"] = false;
        }
        if (!("lockSyncMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lockSyncMode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PolicyDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PolicyDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PolicyDTO(/** @type {Partial<PolicyDTO>} */($$parsedSource));
    }
}

/**
 * ProgressDTO is a live sync-progress snapshot for the flyout.
 */
export class ProgressDTO {
    /**
     * Creates a new ProgressDTO instance.
     * @param {Partial<ProgressDTO>} [$$source = {}] - The source object to create the ProgressDTO.
     */
    constructor($$source = {}) {
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("avgSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avgSpeed"] = 0;
        }
        if (!("doneBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["doneBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("enumerating" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enumerating"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProgressDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressDTO(/** @type {Partial<ProgressDTO>} */($$parsedSource));
    }
}

/**
 * ScheduleDTO is the quiet-hours auto-pause configuration.
 */
export class ScheduleDTO {
    /**
     * Creates a new ScheduleDTO instance.
     * @param {Partial<ScheduleDTO>} [$$source = {}] - The source object to create the ScheduleDTO.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("fromMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromMin"] = 0;
        }
        if (!("toMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toMin"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduleDTO(/** @type {Partial<ScheduleDTO>} */($$parsedSource));
    }
}

/**
 * SearchItem is one unified-search hit for the flyout search bar.
 */
export class SearchItem {
    /**
     * Creates a new SearchItem instance.
     * @param {Partial<SearchItem>} [$$source = {}] - The source object to create the SearchItem.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * file name
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("subline" in $$source)) {
            /**
             * its folder
             * @member
             * @type {string}
             */
            this["subline"] = "";
        }
        if (!("href" in $$source)) {
            /**
             * absolute URL to open it in the browser
             * @member
             * @type {string}
             */
            this["href"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchItem(/** @type {Partial<SearchItem>} */($$parsedSource));
    }
}

/**
 * SetupInfo seeds the post-login configuration screen.
 */
export class SetupInfo {
    /**
     * Creates a new SetupInfo instance.
     * @param {Partial<SetupInfo>} [$$source = {}] - The source object to create the SetupInfo.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("defaultDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultDir"] = "";
        }
        if (!("accountBytes" in $$source)) {
            /**
             * used space on the server ("everything" size)
             * @member
             * @type {number}
             */
            this["accountBytes"] = 0;
        }
        if (!("freeBytes" in $$source)) {
            /**
             * free space on the chosen local volume
             * @member
             * @type {number}
             */
            this["freeBytes"] = 0;
        }
        if (!("onDemandSupport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["onDemandSupport"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SetupInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupInfo(/** @type {Partial<SetupInfo>} */($$parsedSource));
    }
}

/**
 * ShareDTO is an existing share on the target path.
 */
export class ShareDTO {
    /**
     * Creates a new ShareDTO instance.
     * @param {Partial<ShareDTO>} [$$source = {}] - The source object to create the ShareDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * 0 = user, 3 = public link
             * @member
             * @type {number}
             */
            this["type"] = 0;
        }
        if (!("shareWith" in $$source)) {
            /**
             * username (user shares)
             * @member
             * @type {string}
             */
            this["shareWith"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * public-link URL
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["permissions"] = 0;
        }
        if (!("expiration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expiration"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShareDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareDTO(/** @type {Partial<ShareDTO>} */($$parsedSource));
    }
}

/**
 * SidePreview is one side (local or server) of a conflict's content preview.
 */
export class SidePreview {
    /**
     * Creates a new SidePreview instance.
     * @param {Partial<SidePreview>} [$$source = {}] - The source object to create the SidePreview.
     */
    constructor($$source = {}) {
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("isText" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isText"] = false;
        }
        if (!("preview" in $$source)) {
            /**
             * sampled text (UTF-8), empty for binary/missing
             * @member
             * @type {string}
             */
            this["preview"] = "";
        }
        if (!("truncated" in $$source)) {
            /**
             * file is larger than the sample
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("note" in $$source)) {
            /**
             * why there's no text preview (binary / deleted / error)
             * @member
             * @type {string}
             */
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SidePreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SidePreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SidePreview(/** @type {Partial<SidePreview>} */($$parsedSource));
    }
}

/**
 * TrashDTO is a deleted item in the Nextcloud trashbin.
 */
export class TrashDTO {
    /**
     * Creates a new TrashDTO instance.
     * @param {Partial<TrashDTO>} [$$source = {}] - The source object to create the TrashDTO.
     */
    constructor($$source = {}) {
        if (!("href" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["href"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("originalLocation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalLocation"] = "";
        }
        if (!("deletedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deletedAt"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrashDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrashDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrashDTO(/** @type {Partial<TrashDTO>} */($$parsedSource));
    }
}

/**
 * UpdateDTO reports the result of an update check for the Settings UI.
 */
export class UpdateDTO {
    /**
     * Creates a new UpdateDTO instance.
     * @param {Partial<UpdateDTO>} [$$source = {}] - The source object to create the UpdateDTO.
     */
    constructor($$source = {}) {
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("ahead" in $$source)) {
            /**
             * Ahead means the running build is NEWER than the newest release on this
             * channel — what a beta build looks like after opting back out. Without it
             * the UI would claim "you're up to date (v0.1.0.167)" while running .168.
             * @member
             * @type {boolean}
             */
            this["ahead"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * release notes ("what's in this update")
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("err" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["err"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateDTO(/** @type {Partial<UpdateDTO>} */($$parsedSource));
    }
}

/**
 * VersionDTO is a stored version of the version-window's target file.
 */
export class VersionDTO {
    /**
     * Creates a new VersionDTO instance.
     * @param {Partial<VersionDTO>} [$$source = {}] - The source object to create the VersionDTO.
     */
    constructor($$source = {}) {
        if (!("href" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["href"] = "";
        }
        if (!("modified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modified"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionDTO(/** @type {Partial<VersionDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SidePreview.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = LockDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = NotifAction.createFrom;
const $$createType5 = $Create.Array($$createType4);
