// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccountDTO describes the signed-in account for the settings UI.
 */
export class AccountDTO {
    /**
     * Creates a new AccountDTO instance.
     * @param {Partial<AccountDTO>} [$$source = {}] - The source object to create the AccountDTO.
     */
    constructor($$source = {}) {
        if (!("signedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["signedIn"] = false;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountDTO(/** @type {Partial<AccountDTO>} */($$parsedSource));
    }
}

/**
 * AccountEntryDTO is one configured account in the account list.
 */
export class AccountEntryDTO {
    /**
     * Creates a new AccountEntryDTO instance.
     * @param {Partial<AccountEntryDTO>} [$$source = {}] - The source object to create the AccountEntryDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * latest engine status line ("" if not running)
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountEntryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountEntryDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountEntryDTO(/** @type {Partial<AccountEntryDTO>} */($$parsedSource));
    }
}

/**
 * ActivityItem is one recent sync operation.
 */
export class ActivityItem {
    /**
     * Creates a new ActivityItem instance.
     * @param {Partial<ActivityItem>} [$$source = {}] - The source object to create the ActivityItem.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * pair-relative path
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("remotePath" in $$source)) {
            /**
             * files-root-relative path (for sharing)
             * @member
             * @type {string}
             */
            this["remotePath"] = "";
        }
        if (!("err" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["err"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * owning account's user name (set when several accounts are configured)
             * @member
             * @type {string}
             */
            this["account"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActivityItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivityItem(/** @type {Partial<ActivityItem>} */($$parsedSource));
    }
}

/**
 * AppInfo is a Nextcloud app for the flyout (with its pinned state).
 */
export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("href" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["href"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}

/**
 * AttentionInfo counts items needing the user's attention.
 */
export class AttentionInfo {
    /**
     * Creates a new AttentionInfo instance.
     * @param {Partial<AttentionInfo>} [$$source = {}] - The source object to create the AttentionInfo.
     */
    constructor($$source = {}) {
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (!("blocked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["blocked"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttentionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AttentionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttentionInfo(/** @type {Partial<AttentionInfo>} */($$parsedSource));
    }
}

/**
 * BlockedItem is a file that can't sync (server-forbidden name).
 */
export class BlockedItem {
    /**
     * Creates a new BlockedItem instance.
     * @param {Partial<BlockedItem>} [$$source = {}] - The source object to create the BlockedItem.
     */
    constructor($$source = {}) {
        if (!("abs" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["abs"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockedItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlockedItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlockedItem(/** @type {Partial<BlockedItem>} */($$parsedSource));
    }
}

/**
 * BrandDTO carries the white-labellable identity values the frontend shows.
 */
export class BrandDTO {
    /**
     * Creates a new BrandDTO instance.
     * @param {Partial<BrandDTO>} [$$source = {}] - The source object to create the BrandDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("company" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["company"] = "";
        }
        if (!("website" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["website"] = "";
        }
        if (!("support" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["support"] = "";
        }
        if (!("accentHex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accentHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrandDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrandDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrandDTO(/** @type {Partial<BrandDTO>} */($$parsedSource));
    }
}

/**
 * BrowseEntry is a remote folder/file for the folder picker.
 */
export class BrowseEntry {
    /**
     * Creates a new BrowseEntry instance.
     * @param {Partial<BrowseEntry>} [$$source = {}] - The source object to create the BrowseEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowseEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowseEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowseEntry(/** @type {Partial<BrowseEntry>} */($$parsedSource));
    }
}

/**
 * ConflictItem is a pending conflict awaiting a choice, with both versions'
 * size and modified time so the user can decide.
 */
export class ConflictItem {
    /**
     * Creates a new ConflictItem instance.
     * @param {Partial<ConflictItem>} [$$source = {}] - The source object to create the ConflictItem.
     */
    constructor($$source = {}) {
        if (!("localDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("localExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["localExists"] = false;
        }
        if (!("remoteExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["remoteExists"] = false;
        }
        if (!("localSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localSize"] = 0;
        }
        if (!("localMTime" in $$source)) {
            /**
             * "YYYY-MM-DD HH:MM" or ""
             * @member
             * @type {string}
             */
            this["localMTime"] = "";
        }
        if (!("remoteSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remoteSize"] = 0;
        }
        if (!("remoteMTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteMTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictItem(/** @type {Partial<ConflictItem>} */($$parsedSource));
    }
}

/**
 * ConflictPreview holds both versions' content previews so the user can see what
 * they're choosing between, not just sizes and timestamps.
 */
export class ConflictPreview {
    /**
     * Creates a new ConflictPreview instance.
     * @param {Partial<ConflictPreview>} [$$source = {}] - The source object to create the ConflictPreview.
     */
    constructor($$source = {}) {
        if (!("local" in $$source)) {
            /**
             * @member
             * @type {SidePreview}
             */
            this["local"] = (new SidePreview());
        }
        if (!("remote" in $$source)) {
            /**
             * @member
             * @type {SidePreview}
             */
            this["remote"] = (new SidePreview());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictPreview}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local" in $$parsedSource) {
            $$parsedSource["local"] = $$createField0_0($$parsedSource["local"]);
        }
        if ("remote" in $$parsedSource) {
            $$parsedSource["remote"] = $$createField1_0($$parsedSource["remote"]);
        }
        return new ConflictPreview(/** @type {Partial<ConflictPreview>} */($$parsedSource));
    }
}

/**
 * DiagnosticsDTO is a connection/sync health snapshot for the health panel.
 */
export class DiagnosticsDTO {
    /**
     * Creates a new DiagnosticsDTO instance.
     * @param {Partial<DiagnosticsDTO>} [$$source = {}] - The source object to create the DiagnosticsDTO.
     */
    constructor($$source = {}) {
        if (!("serverURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverURL"] = "";
        }
        if (!("serverVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverVersion"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account"] = "";
        }
        if (!("pushAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pushAvailable"] = false;
        }
        if (!("pushConnected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pushConnected"] = false;
        }
        if (!("pushUptime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pushUptime"] = "";
        }
        if (!("lastStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastStatus"] = "";
        }
        if (!("lastSync" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSync"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticsDTO(/** @type {Partial<DiagnosticsDTO>} */($$parsedSource));
    }
}

/**
 * FlyoutAppearanceDTO carries the flyout's appearance settings to the UI.
 */
export class FlyoutAppearanceDTO {
    /**
     * Creates a new FlyoutAppearanceDTO instance.
     * @param {Partial<FlyoutAppearanceDTO>} [$$source = {}] - The source object to create the FlyoutAppearanceDTO.
     */
    constructor($$source = {}) {
        if (!("dockIconSize" in $$source)) {
            /**
             * small | medium | large
             * @member
             * @type {string}
             */
            this["dockIconSize"] = "";
        }
        if (!("panelWidth" in $$source)) {
            /**
             * compact | standard | wide
             * @member
             * @type {string}
             */
            this["panelWidth"] = "";
        }
        if (!("density" in $$source)) {
            /**
             * comfortable | compact
             * @member
             * @type {string}
             */
            this["density"] = "";
        }
        if (!("sections" in $$source)) {
            /**
             * ordered visible middle sections
             * @member
             * @type {string[]}
             */
            this["sections"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlyoutAppearanceDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FlyoutAppearanceDTO}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sections" in $$parsedSource) {
            $$parsedSource["sections"] = $$createField3_0($$parsedSource["sections"]);
        }
        return new FlyoutAppearanceDTO(/** @type {Partial<FlyoutAppearanceDTO>} */($$parsedSource));
    }
}

/**
 * FolderInfo is a synced folder for the flyout's quick buttons.
 */
export class FolderInfo {
    /**
     * Creates a new FolderInfo instance.
     * @param {Partial<FolderInfo>} [$$source = {}] - The source object to create the FolderInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("localDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderInfo(/** @type {Partial<FolderInfo>} */($$parsedSource));
    }
}

/**
 * HeaderInfo describes the signed-in user and their Nextcloud presence.
 */
export class HeaderInfo {
    /**
     * Creates a new HeaderInfo instance.
     * @param {Partial<HeaderInfo>} [$$source = {}] - The source object to create the HeaderInfo.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("statusType" in $$source)) {
            /**
             * online | away | dnd | invisible | offline
             * @member
             * @type {string}
             */
            this["statusType"] = "";
        }
        if (!("statusMsg" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusMsg"] = "";
        }
        if (!("statusIcon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusIcon"] = "";
        }
        if (!("quotaUsed" in $$source)) {
            /**
             * bytes used
             * @member
             * @type {number}
             */
            this["quotaUsed"] = 0;
        }
        if (!("quotaTotal" in $$source)) {
            /**
             * effective total bytes (0 if unknown)
             * @member
             * @type {number}
             */
            this["quotaTotal"] = 0;
        }
        if (!("quotaPct" in $$source)) {
            /**
             * percent used (0–100)
             * @member
             * @type {number}
             */
            this["quotaPct"] = 0;
        }
        if (!("unlimited" in $$source)) {
            /**
             * no configured quota
             * @member
             * @type {boolean}
             */
            this["unlimited"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeaderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HeaderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeaderInfo(/** @type {Partial<HeaderInfo>} */($$parsedSource));
    }
}

/**
 * LimitsDTO is the bandwidth configuration (KiB/s; 0 = unlimited).
 */
export class LimitsDTO {
    /**
     * Creates a new LimitsDTO instance.
     * @param {Partial<LimitsDTO>} [$$source = {}] - The source object to create the LimitsDTO.
     */
    constructor($$source = {}) {
        if (!("up" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["up"] = 0;
        }
        if (!("down" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["down"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LimitsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LimitsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LimitsDTO(/** @type {Partial<LimitsDTO>} */($$parsedSource));
    }
}

/**
 * NotifAction is a button on a notification.
 */
export class NotifAction {
    /**
     * Creates a new NotifAction instance.
     * @param {Partial<NotifAction>} [$$source = {}] - The source object to create the NotifAction.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotifAction}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotifAction(/** @type {Partial<NotifAction>} */($$parsedSource));
    }
}

/**
 * NotifItem is a Nextcloud notification.
 */
export class NotifItem {
    /**
     * Creates a new NotifItem instance.
     * @param {Partial<NotifItem>} [$$source = {}] - The source object to create the NotifItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("app" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {NotifAction[]}
             */
            this["actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotifItem}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField5_0($$parsedSource["actions"]);
        }
        return new NotifItem(/** @type {Partial<NotifItem>} */($$parsedSource));
    }
}

/**
 * OfflineEntry is one folder in the "available offline" browser.
 */
export class OfflineEntry {
    /**
     * Creates a new OfflineEntry instance.
     * @param {Partial<OfflineEntry>} [$$source = {}] - The source object to create the OfflineEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rel"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OfflineEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OfflineEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OfflineEntry(/** @type {Partial<OfflineEntry>} */($$parsedSource));
    }
}

/**
 * OtherAttention reports a background account with pending conflicts or
 * blocked files, so the Status window can point at it.
 */
export class OtherAttention {
    /**
     * Creates a new OtherAttention instance.
     * @param {Partial<OtherAttention>} [$$source = {}] - The source object to create the OtherAttention.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (!("blocked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["blocked"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OtherAttention instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OtherAttention}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OtherAttention(/** @type {Partial<OtherAttention>} */($$parsedSource));
    }
}

/**
 * PairDTO describes a configured sync pair.
 */
export class PairDTO {
    /**
     * Creates a new PairDTO instance.
     * @param {Partial<PairDTO>} [$$source = {}] - The source object to create the PairDTO.
     */
    constructor($$source = {}) {
        if (!("localDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDir"] = "";
        }
        if (!("remoteRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteRoot"] = "";
        }
        if (!("excludes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["excludes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PairDTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("excludes" in $$parsedSource) {
            $$parsedSource["excludes"] = $$createField2_0($$parsedSource["excludes"]);
        }
        return new PairDTO(/** @type {Partial<PairDTO>} */($$parsedSource));
    }
}

/**
 * PauseDTO mirrors the engine's effective pause state for the UI.
 */
export class PauseDTO {
    /**
     * Creates a new PauseDTO instance.
     * @param {Partial<PauseDTO>} [$$source = {}] - The source object to create the PauseDTO.
     */
    constructor($$source = {}) {
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("until" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["until"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PauseDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PauseDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PauseDTO(/** @type {Partial<PauseDTO>} */($$parsedSource));
    }
}

/**
 * PolicyDTO tells the UI which settings are admin-managed so it can lock them.
 */
export class PolicyDTO {
    /**
     * Creates a new PolicyDTO instance.
     * @param {Partial<PolicyDTO>} [$$source = {}] - The source object to create the PolicyDTO.
     */
    constructor($$source = {}) {
        if (!("managed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["managed"] = false;
        }
        if (!("lockServer" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lockServer"] = false;
        }
        if (!("serverUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverUrl"] = "";
        }
        if (!("allowSignOut" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allowSignOut"] = false;
        }
        if (!("lockBandwidth" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lockBandwidth"] = false;
        }
        if (!("lockSyncMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lockSyncMode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PolicyDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PolicyDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PolicyDTO(/** @type {Partial<PolicyDTO>} */($$parsedSource));
    }
}

/**
 * ProgressDTO is a live sync-progress snapshot for the flyout.
 */
export class ProgressDTO {
    /**
     * Creates a new ProgressDTO instance.
     * @param {Partial<ProgressDTO>} [$$source = {}] - The source object to create the ProgressDTO.
     */
    constructor($$source = {}) {
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("avgSpeed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avgSpeed"] = 0;
        }
        if (!("doneBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["doneBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("enumerating" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enumerating"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProgressDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressDTO(/** @type {Partial<ProgressDTO>} */($$parsedSource));
    }
}

/**
 * ScheduleDTO is the quiet-hours auto-pause configuration.
 */
export class ScheduleDTO {
    /**
     * Creates a new ScheduleDTO instance.
     * @param {Partial<ScheduleDTO>} [$$source = {}] - The source object to create the ScheduleDTO.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("fromMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromMin"] = 0;
        }
        if (!("toMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toMin"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduleDTO(/** @type {Partial<ScheduleDTO>} */($$parsedSource));
    }
}

/**
 * SearchItem is one unified-search hit for the flyout search bar.
 */
export class SearchItem {
    /**
     * Creates a new SearchItem instance.
     * @param {Partial<SearchItem>} [$$source = {}] - The source object to create the SearchItem.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * file name
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("subline" in $$source)) {
            /**
             * its folder
             * @member
             * @type {string}
             */
            this["subline"] = "";
        }
        if (!("href" in $$source)) {
            /**
             * absolute URL to open it in the browser
             * @member
             * @type {string}
             */
            this["href"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchItem(/** @type {Partial<SearchItem>} */($$parsedSource));
    }
}

/**
 * SetupInfo seeds the post-login configuration screen.
 */
export class SetupInfo {
    /**
     * Creates a new SetupInfo instance.
     * @param {Partial<SetupInfo>} [$$source = {}] - The source object to create the SetupInfo.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("defaultDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultDir"] = "";
        }
        if (!("accountBytes" in $$source)) {
            /**
             * used space on the server ("everything" size)
             * @member
             * @type {number}
             */
            this["accountBytes"] = 0;
        }
        if (!("freeBytes" in $$source)) {
            /**
             * free space on the chosen local volume
             * @member
             * @type {number}
             */
            this["freeBytes"] = 0;
        }
        if (!("onDemandSupport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["onDemandSupport"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SetupInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupInfo(/** @type {Partial<SetupInfo>} */($$parsedSource));
    }
}

/**
 * ShareDTO is an existing share on the target path.
 */
export class ShareDTO {
    /**
     * Creates a new ShareDTO instance.
     * @param {Partial<ShareDTO>} [$$source = {}] - The source object to create the ShareDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * 0 = user, 3 = public link
             * @member
             * @type {number}
             */
            this["type"] = 0;
        }
        if (!("shareWith" in $$source)) {
            /**
             * username (user shares)
             * @member
             * @type {string}
             */
            this["shareWith"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * public-link URL
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["permissions"] = 0;
        }
        if (!("expiration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expiration"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShareDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareDTO(/** @type {Partial<ShareDTO>} */($$parsedSource));
    }
}

/**
 * SidePreview is one side (local or server) of a conflict's content preview.
 */
export class SidePreview {
    /**
     * Creates a new SidePreview instance.
     * @param {Partial<SidePreview>} [$$source = {}] - The source object to create the SidePreview.
     */
    constructor($$source = {}) {
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("isText" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isText"] = false;
        }
        if (!("preview" in $$source)) {
            /**
             * sampled text (UTF-8), empty for binary/missing
             * @member
             * @type {string}
             */
            this["preview"] = "";
        }
        if (!("truncated" in $$source)) {
            /**
             * file is larger than the sample
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("note" in $$source)) {
            /**
             * why there's no text preview (binary / deleted / error)
             * @member
             * @type {string}
             */
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SidePreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SidePreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SidePreview(/** @type {Partial<SidePreview>} */($$parsedSource));
    }
}

/**
 * TrashDTO is a deleted item in the Nextcloud trashbin.
 */
export class TrashDTO {
    /**
     * Creates a new TrashDTO instance.
     * @param {Partial<TrashDTO>} [$$source = {}] - The source object to create the TrashDTO.
     */
    constructor($$source = {}) {
        if (!("href" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["href"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("originalLocation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalLocation"] = "";
        }
        if (!("deletedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deletedAt"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrashDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrashDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrashDTO(/** @type {Partial<TrashDTO>} */($$parsedSource));
    }
}

/**
 * UpdateDTO reports the result of an update check for the Settings UI.
 */
export class UpdateDTO {
    /**
     * Creates a new UpdateDTO instance.
     * @param {Partial<UpdateDTO>} [$$source = {}] - The source object to create the UpdateDTO.
     */
    constructor($$source = {}) {
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * release notes ("what's in this update")
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("err" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["err"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateDTO(/** @type {Partial<UpdateDTO>} */($$parsedSource));
    }
}

/**
 * VersionDTO is a stored version of the version-window's target file.
 */
export class VersionDTO {
    /**
     * Creates a new VersionDTO instance.
     * @param {Partial<VersionDTO>} [$$source = {}] - The source object to create the VersionDTO.
     */
    constructor($$source = {}) {
        if (!("href" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["href"] = "";
        }
        if (!("modified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modified"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionDTO(/** @type {Partial<VersionDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SidePreview.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = NotifAction.createFrom;
const $$createType3 = $Create.Array($$createType2);
