// Android adaptive-icon output.
//
// The same artwork as the desktop .ico, emitted as VectorDrawables instead of
// PNGs: the Android project deliberately carries no raster assets, and this
// icon is circles, a rectangle and a linear gradient — all of which a vector
// expresses exactly. One source of truth, so a white-label accent will later
// regenerate the phone icon as well as the desktop one.
package main

import (
	"bytes"
	"fmt"
	"image/color"
	"math"
	"os"
	"path/filepath"
	"strings"
)

// Adaptive icons are 108x108dp with only the centre 66x66dp guaranteed visible;
// everything outside can be cropped by whatever mask the launcher applies.
const (
	adaptiveViewport = 108.0
	adaptiveSafe     = 66.0
)

// shape is one primitive of the nimbus, in the same fractional units drawCloud
// uses, so the two renderings cannot drift.
type shape struct {
	cx, cy, r      float64 // disc
	x0, y0, x1, y1 float64 // rect / pill
	round          float64
	col            color.RGBA
	isRect         bool
}

// cloudShapes mirrors drawCloud exactly, in units of the tile side f = 1.
// Painter's order: deep-gold underside first, then the light-gold body over it.
func cloudShapes() []shape {
	cx, cy := 0.52, 0.54
	s := []shape{
		{cx: cx - 0.205, cy: cy + 0.045, r: 0.095, col: goldDeep},
		{cx: cx - 0.045, cy: cy + 0.065, r: 0.105, col: goldDeep},
		{cx: cx + 0.115, cy: cy + 0.060, r: 0.100, col: goldDeep},
		{cx: cx + 0.245, cy: cy + 0.030, r: 0.080, col: goldDeep},
		{x0: cx - 0.205, y0: cy - 0.045, x1: cx + 0.245, y1: cy + 0.045, col: goldLight, isRect: true},
		{cx: cx - 0.205, cy: cy, r: 0.078, col: goldLight},
		{cx: cx + 0.245, cy: cy, r: 0.066, col: goldLight},
		{cx: cx - 0.125, cy: cy - 0.065, r: 0.105, col: goldLight},
		{cx: cx + 0.020, cy: cy - 0.100, r: 0.130, col: goldLight},
		{cx: cx + 0.165, cy: cy - 0.050, r: 0.095, col: goldLight},
	}
	// The speed streaks, as pills. The desktop draws these only at >= 24px; a
	// vector has no such floor, so they are always present here.
	s = append(s,
		pillShape(cx-0.42, cy-0.075, cx-0.27, 0.040, goldLight),
		pillShape(cx-0.46, cy+0.010, cx-0.33, 0.040, goldLight),
		pillShape(cx-0.40, cy+0.095, cx-0.29, 0.040, goldDeep),
	)
	return s
}

func pillShape(x0, y, x1, h float64, col color.RGBA) shape {
	return shape{
		x0: x0, y0: y - h/2, x1: x1, y1: y + h/2,
		round: h / 2, col: col, isRect: true,
	}
}

// artworkBounds returns the drawn extent in fractional units.
func artworkBounds(shapes []shape) (minX, minY, maxX, maxY float64) {
	minX, minY = math.Inf(1), math.Inf(1)
	maxX, maxY = math.Inf(-1), math.Inf(-1)
	for _, s := range shapes {
		var a, b, c, d float64
		if s.isRect {
			a, b, c, d = s.x0, s.y0, s.x1, s.y1
		} else {
			a, b, c, d = s.cx-s.r, s.cy-s.r, s.cx+s.r, s.cy+s.r
		}
		minX, minY = math.Min(minX, a), math.Min(minY, b)
		maxX, maxY = math.Max(maxX, c), math.Max(maxY, d)
	}
	return
}

// writeAndroid emits the adaptive-icon layers into an Android res/ directory.
func writeAndroid(res string) {
	dir := filepath.Join(res, "drawable")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		panic(err)
	}
	writeFile(filepath.Join(dir, "ic_launcher_background.xml"), backgroundVector())
	writeFile(filepath.Join(dir, "ic_launcher_foreground.xml"), cloudVector(false))
	writeFile(filepath.Join(dir, "ic_launcher_monochrome.xml"), cloudVector(true))
	fmt.Println("wrote adaptive icon layers to", dir)
}

func writeFile(path, body string) {
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		panic(err)
	}
}

// backgroundVector is the tile gradient, full-bleed: the launcher applies its
// own mask, so artwork carrying its own corners would show as a dark ring
// inside a circular one.
func backgroundVector() string {
	return fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by shell/windows/appicon — do not edit by hand.
     Regenerate: cd shell/windows/appicon && go run . android <res-dir>
     The desktop tile gradient, full-bleed. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:startX="54" android:startY="0"
                android:endX="54" android:endY="108"
                android:type="linear">
                <item android:offset="0" android:color="%s" />
                <item android:offset="1" android:color="%s" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
`, hexOf(indigoTop), hexOf(indigoBot))
}

// cloudVector is the nimbus alone on transparency, scaled and centred into the
// adaptive icon's safe zone. mono flattens it to one colour for themed icons,
// which the platform tints itself.
func cloudVector(mono bool) string {
	shapes := cloudShapes()
	minX, minY, maxX, maxY := artworkBounds(shapes)
	w, h := maxX-minX, maxY-minY

	// Fit inside the safe zone with a little air, so it does not graze the edge
	// of a circular mask.
	const fill = 0.92
	scale := (adaptiveSafe * fill) / math.Max(w, h)
	// Centre what is actually drawn, not the nominal tile centre: the speed
	// streaks make the artwork lopsided, and centring the tile would push the
	// cloud to the right.
	offX := adaptiveViewport/2 - (minX+w/2)*scale
	offY := adaptiveViewport/2 - (minY+h/2)*scale

	kind := "foreground"
	if mono {
		kind = "monochrome"
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by shell/windows/appicon — do not edit by hand.
     Regenerate: cd shell/windows/appicon && go run . android <res-dir>
     The %s layer: the desktop's golden nimbus, fitted to the 66dp safe zone. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
`, kind)
	for _, s := range shapes {
		col := hexOf(s.col)
		if mono {
			// One flat silhouette; the system supplies the colour.
			col = "#FFFFFFFF"
		}
		fmt.Fprintf(&b, "    <path android:fillColor=%q android:pathData=%q />\n",
			col, pathData(s, scale, offX, offY))
	}
	b.WriteString("</vector>\n")
	return b.String()
}

// pathData renders one shape as SVG path data in viewport units.
func pathData(s shape, scale, offX, offY float64) string {
	tx := func(v float64) float64 { return v*scale + offX }
	ty := func(v float64) float64 { return v*scale + offY }
	if !s.isRect {
		cx, cy, r := tx(s.cx), ty(s.cy), s.r*scale
		// Two half-arcs make a full circle; a single 360-degree arc is degenerate.
		return fmt.Sprintf("M%s,%s a%s,%s 0 1,0 %s,0 a%s,%s 0 1,0 -%s,0 Z",
			n(cx-r), n(cy), n(r), n(r), n(2*r), n(r), n(r), n(2*r))
	}
	x0, y0, x1, y1 := tx(s.x0), ty(s.y0), tx(s.x1), ty(s.y1)
	if s.round <= 0 {
		return fmt.Sprintf("M%s,%s H%s V%s H%s Z", n(x0), n(y0), n(x1), n(y1), n(x0))
	}
	r := s.round * scale
	return fmt.Sprintf("M%s,%s H%s a%s,%s 0 0,1 0,%s H%s a%s,%s 0 0,1 0,-%s Z",
		n(x0), n(y0), n(x1-r), n(r), n(r), n(2*r), n(x0+r), n(r), n(r), n(2*r))
}

// n formats a coordinate compactly — trailing zeros in generated XML are noise.
func n(v float64) string {
	s := fmt.Sprintf("%.2f", v)
	if strings.Contains(s, ".") {
		s = strings.TrimRight(s, "0")
		s = strings.TrimSuffix(s, ".")
	}
	return s
}

func hexOf(c color.RGBA) string {
	return fmt.Sprintf("#%02X%02X%02X%02X", c.A, c.R, c.G, c.B)
}
